# split panes
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload
bind r source-file ~/.tmux.conf

# pane navigation
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection

# general settings
set -g allow-rename off
set -g history-limit 30000
set -g default-shell /bin/zsh
set -sg escape-time 10
set -g default-terminal "screen-256color"

# mouse toggle
bind M set -g mouse on \; display-message "Mouse: ON"
bind m set -g mouse off \; display-message "Mouse: OFF"
